#ifndef LANGUAGETRANSLATOR_GLOBAL_H
#define LANGUAGETRANSLATOR_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LANGUAGETRANSLATOR_LIBRARY)
#  define LANGUAGETRANSLATORSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LANGUAGETRANSLATORSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LANGUAGETRANSLATOR_GLOBAL_H
