#ifndef CAUDIOLYRICS_GLOBAL_H
#define CAUDIOLYRICS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CAUDIOLYRICS_LIBRARY)
#  define CAUDIOLYRICSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CAUDIOLYRICSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CAUDIOLYRICS_GLOBAL_H
